server {
    listen 80;
    server_name 127.0.0.1;

    location /testblock.txt {
        alias /usr/local/kong/files/testblock.txt;
        access_log /usr/local/kong/logs/testblock_access.log;
        error_log /usr/local/kong/logs/testblock_error.log;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
        sendfile off; # ปิด sendfile เพื่อให้ Nginx อ่านไฟล์ใหม่ทุกครั้ง
    }
}